### ISSUE TITLE
missedBlocks is getting from config instead of node state

### ISSUE THREAD

**Issue by alepop** [sidechain-solutions/lisk-dfc#1]
**Expected behaviour:**
`missedBlocks` should be getting from the `state.json` file
**Actual behaviour:**
`missedBlocks` getting from from the `config.json` file
https://github.com/sidechain-solutions/lisk-dfc/blob/0ceb5d2e38b4ed3863e4beeeba67ebcf60750a2b/index.js#L48-L54

**Comment by Lemii** [comment]
Thank you for pointing this out @alepop . This issue is now been fixed with https://github.com/sidechain-solutions/lisk-dfc/commit/0e32c7ad94ea0b2654b4ad38c671e673f14f85fb.
